Revert "msm_bus: remove tracer"
This commit fixed the folliwing issue when LTO:

drivers/soc/qcom/msm_bus/msm_bus_dbg_rpmh.o: in function `__read_once_size':
/home/ayrton/pe/kernel/xiaomi/sm8250/out/../include/linux/compiler.h:207: undefined reference to `__tracepoint_bus_update_request'

This reverts commit f96f72295afed72993d2604008473db0621fd124.

Signed-off-by: Carlos Ayrton Lopez Arroyo <15030201@itcelaya.edu.mx>